version: '3.8'

# Configuration pour l'environnement STAGING
services:
  mnist-backend:
    environment:
      - ENV=staging
      - DEBUG=true
      - LOG_LEVEL=debug
    volumes:
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.5'

  mnist-frontend:
    environment:
      - ENV=staging
      - API_URL=http://mnist-backend:8000
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_LOGGER_LEVEL=debug
    ports:
      - "8501:8501"
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.3'

  # Service de monitoring pour staging
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus-staging.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'

networks:
  default:
    name: mnist-staging-network 