services:
  mnist-backend:
    image: ${BACKEND_IMAGE:-ghcr.io/nicoooo972/mnist-backend:latest}
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  mnist-frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/nicoooo972/mnist-frontend:latest}
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://mnist-backend:8000
    depends_on:
      mnist-backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  default:
    name: mnist-network
